import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";
import styles from "./globals.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={styles.body}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
